allowBuilds:
  '@firebase/util': true
  cpu-features: true
  protobufjs: true
  re2: true
  ssh2: true
  unrs-resolver: true
minimumReleaseAge: 1440 # 1 day
trustPolicy: no-downgrade
trustPolicyExclude:
  - jose@4.15.9
  - semver@6.3.1
